# .github/workflows/ci.yml

name: Shortly Full Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Frontend Validation
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Frontend & Lint
        run: npm ci && npm run lint
        working-directory: ./frontend
      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      # Backend Validation
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Backend & Lint
        run: |
          pip install -r requirements.txt
          flake8 .
          black --check .
        working-directory: ./backend
      - name: Run Backend Tests
        # Run pytest from the root, pointing to the backend tests.
        run: pytest backend/
  
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push unified Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shortly-app:latest